export const CATEGORIES_ACTION_TYPES = {
    //SET_CATEGORIES: 'categories/SET_CATEGORIES_MAP',
    FETCH_CATEGORIES_START: 'Category/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCESS: 'Category/FETCH_CATEGORIES_SUCESS',
    FETCH_CATEGORIES_FAILED: 'Category/FETCH_CATEGORIES_FAILED',
  };